spring.application.name=movies
spring.datasource.url=jdbc:postgresql://localhost:5432/moviedb
spring.datasource.username=postgres
spring.datasource.password=pperadetlic8
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
