spring.application.name=movies
spring.datasource.url=jdbc:postgresql://localhost:5432/moviedb
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
api.key=
